name: CI Build

on:
  push:
    branches:
      - ci-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: 更新包管理器并安装 xmake 和 Python 依赖
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo add-apt-repository ppa:xmake-io/xmake -y
          sudo apt update
          sudo apt install -y nim
          sudo apt install -y xmake python3-pip
          pip install --upgrade pip
          pip install kconfiglib scons requests tqdm psutil

      # Step 3: 设置环境并运行 xmake 进行编译
      - name: Setup Environment and Build
        run: |
          # 使用 bash 作为 shell
          bash -c '
          source env.sh
          cd models
          xmake -vyD
          '
        shell: bash
