name: CI Build

on:
  push:
    branches:
      - ci-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo add-apt-repository ppa:xmake-io/xmake -y
          sudo apt update
          sudo apt install -y nim
          sudo apt install -y xmake python3-pip qemu-system-aarch64
          pip install --upgrade pip
          pip install kconfiglib scons requests tqdm psutil

      - name: Setup Environment and Build
        run: |
          # 使用 bash 作为 shell
          bash -c '
          source env.sh
          cd models
          xmake -vyD
          '
        shell: bash

      - name: Set file permissions
        run: |
          chmod +r ./models/rtthread.bin
          chmod +r ./models/build/ext4.img

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./models/rtthread.bin
            ./models/build/ext4.img
          retention-days: 7

      - name: Verify Build with QEMU
        run: |
          qemu-system-aarch64 -M virt,gic-version=2 -cpu cortex-a53 -m 128M -smp 4 -kernel ./models/rtthread.bin -nographic \
          -drive if=none,file=./models/build/ext4.img,format=raw,id=blk0 \
          -device virtio-blk-device,drive=blk0,bus=virtio-mmio-bus.0 \
          -netdev user,id=net0 -device virtio-net-device,netdev=net0,bus=virtio-mmio-bus.1 \
          -device virtio-serial-device \
          -chardev socket,host=127.0.0.1,port=4321,server=on,wait=off,telnet=on,id=console0 \
          -device virtserialport,chardev=console0
          